setwd('~/Desktop/RWS_0001-0096_outin/R_more100')
library('ape')
library('phyloseqCompanion')
#library("phyloseq")
#library("foreach")
#library("iterators")
#library("parallel")
#library("doParallel")
library("ggplot2")
library("plyr")
#library("vegan")
data.all <- read.table('OTUtable_ingroup.txt')
mytable = otu_table(data.all, taxa_are_rows=TRUE,errorIfNULL=TRUE)
env.all <- read.table('NBP1910_envdata.txt')
envdata = sample_data(env.all)
tree <- read.tree('rename.tree')
phy_tree(tree, errorIfNULL=TRUE)
test = read.table("Blast_result_renamed.txt", header=TRUE)
testb <- as.matrix(test[,-1])
TAX <- tax_table(testb)
physeq <- phyloseq(mytable, envdata, tree, TAX)
Mixo <- subset_taxa(physeq, trophic == "Mixo")
Het <- subset_taxa(physeq, trophic == "Hetero")
Photo <- subset_taxa(physeq, trophic == "Photo")
#PCoA <- ordinate(physeq, "PCoA", distance = "canberra")
dUNIFRAC = UniFrac(physeq, weighted=TRUE, normalized=FALSE, fast=TRUE)
PCoA <- ordinate(physeq, "PCoA", distance = dUNIFRAC)
ordplotP <- plot_ordination(physeq, PCoA, color="Lat", shape="size",label="sample",title="All")
ordplotPplus <- ordplotP + geom_point(size=3) + stat_ellipse(geom = "polygon", type="norm", alpha=0.2, aes(fill=size))
quartz()
plot(ordplotPplus)

#PCoAm <- ordinate(micro, "PCoA", distance = "canberra")
dUNIFRACm = UniFrac(Mixo, weighted=FALSE, normalized=TRUE, fast=TRUE)
PCoAm <- ordinate(Mixo, "PCoA", distance = dUNIFRACm)
ordplotPm <- plot_ordination(Mixo, PCoAm, color="Lat", shape="size",label="sample",title="Mixo")
ordplotPmplus <- ordplotPm + geom_point(size=3) + stat_ellipse(geom = "polygon", type="norm", alpha=0.2, aes(fill=depth))
quartz()
plot(ordplotPmplus)

#PCoAn <- ordinate(nano, "PCoA", distance = "canberra")
dUNIFRACh = UniFrac(Het, weighted=FALSE, normalized=TRUE, fast=TRUE)
PCoAh <- ordinate(Het, "PCoA", distance = dUNIFRACh)
ordplotPh <- plot_ordination(Het, PCoAh, color="Lat", shape="size",label="sample",title="Het")
quartz()
ordplotPhplus <- ordplotPh + geom_point(size=3) + stat_ellipse(geom = "polygon", type="norm", alpha=0.2, aes(fill=depth))
plot(ordplotPhplus)

#PCoAn <- ordinate(nano, "PCoA", distance = "canberra")
dUNIFRACp = UniFrac(Photo, weighted=FALSE, normalized=TRUE, fast=TRUE)
PCoAp <- ordinate(Photo, "PCoA", distance = dUNIFRACp)
ordplotPp <- plot_ordination(Photo, PCoAp, color="Lat", shape="size",label="sample",title="Photo")
quartz()
ordplotPpplus <- ordplotPp + geom_point(size=3) + stat_ellipse(geom = "polygon", type="norm", alpha=0.2, aes(fill=depth))
plot(ordplotPpplus)
#quartz()
#map.df <- data.frame(sample_data(physeq))
#orddataPa <- ordplotP$data
#ordPpa.ef <- envfit(PCoA$vectors~station,permutations=1000,data= map.df)
#ordPca.ef <- envfit(PCoA$vectors~size,permutations=1000,data= map.df)
#plot(x=orddataPa$Axis.1, y=orddataPa$Axis.2,type="n")
#points(PCoA$vectors[,1],PCoA$vectors[,2], cex=0.5, col=map.df$size, pch=19)
#ordiellipse(PCoA$vectors, map.df$size,label=TRUE,cex=0.7,conf=0.99,col="yellow")
