setwd('/home/tuk61790/HPCr/')
library('phytools')
library('phyloseqCompanion')
#library("phyloseq")
#library("foreach")
#library("iterators")
#library("parallel")
#library("doParallel")
#library("vegan")
library("ggplot2")
library("plyr")
data.all <- read.table('OTUtable_temp.txt')
mytable = otu_table(data.all, taxa_are_rows=TRUE,errorIfNULL=TRUE)
env.all <- read.table('NBP1910_envdataCTD_2021.txt')
envdata = sample_data(env.all)
tree <- phytools::read.newick('rename2.tree')
phy_tree(tree, errorIfNULL=TRUE)
test = read.table("VTaxo.txt", header=TRUE)
testb <- as.matrix(test[,-1])
TAX <- tax_table(testb)
physeq <- phyloseq(mytable, envdata, tree, TAX)
pico <- subset_samples(physeq, size == "pico")
nano <- subset_samples(physeq, size == "nano")
micro <- subset_samples(physeq, size == "micro")
#PCoA <- ordinate(physeq, "PCoA", distance = "canberra")
dUNIFRAC = UniFrac(physeq, weighted=TRUE, normalized=FALSE, fast=TRUE)
PCoA <- ordinate(physeq, "PCoA", distance = dUNIFRAC)
ordplotP <- plot_ordination(physeq, PCoA, color="Lat", shape="size",label="sample", title="Allsize")
ordplotPplus <- ordplotP + geom_point(size=3) + stat_ellipse(geom = "polygon", type="norm", alpha=0.4, aes(fill=size))
quartz()
plot(ordplotPplus)

#PCoAm <- ordinate(micro, "PCoA", distance = "canberra")
dUNIFRACm = UniFrac(micro, weighted=TRUE, normalized=FALSE, fast=TRUE)
PCoAm <- ordinate(micro, "PCoA", distance = dUNIFRACm)
ordplotPm <- plot_ordination(micro, PCoAm, color="Lat", shape="depth",label="sample",title="Micropk")
ordplotPmplus <- ordplotPm + geom_point(size=3) + stat_ellipse(geom = "polygon", type="norm", alpha=0.4, aes(fill=depth))
quartz()
plot(ordplotPmplus)

#PCoAn <- ordinate(nano, "PCoA", distance = "canberra")
dUNIFRACn = UniFrac(nano, weighted=TRUE, normalized=FALSE, fast=TRUE)
PCoAn <- ordinate(nano, "PCoA", distance = dUNIFRACn)
ordplotPn <- plot_ordination(nano, PCoAn, color="Lat", shape="depth",label="sample",title="Nanopk")
quartz()
plot(ordplotPn)

#PCoAn <- ordinate(nano, "PCoA", distance = "canberra")
dUNIFRACp = UniFrac(pico, weighted=TRUE, normalized=FALSE, fast=TRUE)
PCoAp <- ordinate(pico, "PCoA", distance = dUNIFRACp)
ordplotPp <- plot_ordination(pico, PCoAp, color="Lat", shape="depth",label="sample",title="Picopk")
quartz()
plot(ordplotPp)

#quartz()
#map.df <- data.frame(sample_data(physeq))
#orddataPa <- ordplotP$data
#ordPpa.ef <- envfit(PCoA$vectors~station,permutations=1000,data= map.df)
#ordPca.ef <- envfit(PCoA$vectors~size,permutations=1000,data= map.df)
#plot(x=orddataPa$Axis.1, y=orddataPa$Axis.2,type="n")
#points(PCoA$vectors[,1],PCoA$vectors[,2], cex=0.5, col=map.df$size, pch=19)
#ordiellipse(PCoA$vectors, map.df$size,label=TRUE,cex=0.7,conf=0.99,col="yellow")

ordMDS <- metaMDS(t(otu_table(physeq)))
ordMDS.fit <- envfit(ordMDS ~ Lat + Long + bprod + pprod_Sun + pprod_PAR + ice + airT + depth_m + PAR1 + PAR2 + salinity1 + timeJ + latitude + longitude + oxygen1 + oxygenSaturation + fluorescence + beamTrans + waterT1 + conductivity1 + depSM + size_num, data=sample.data.table(physeq), perm=999, na.rm = TRUE)
plot(ordMDS, dis="site")
plot(ordMDS.fit)
text(ordMDS, display="sites")
ordMDS.fit
