setwd('/Users/jaydiii/Desktop/JD_desktop/R_MiSeq/R_all')
library('ape')
library('phytools')
library('phyloseqCompanion')
library("ggplot2")
library("plyr")
#library("phyloseq")
#library("foreach")
#library("iterators")
#library("parallel")
#library("doParallel")
#library("vegan")
data.all <- read.table('OTUtable_temp.txt')
mytable = otu_table(data.all, taxa_are_rows=TRUE,errorIfNULL=TRUE)
env.all <- read.table('NBP1910_envdataCTD_2021c.txt')
#env.all.sc <- scale(env.all)
#attr(env.all.sc, "scaled:center") <- NULL
#attr(env.all.sc, "scaled:scale") <- NULL
#envdata = sample_data(data.frame(env.all.sc))
## 5 is the column size (non numeric so not scalable)
envdata = sample_data(data.frame(cbind(data.frame(scale(env.all[c(5:22)])),env.all[c(1:4)])))
tree <- phytools::read.newick('rename2.tree')
phy_tree(tree, errorIfNULL=TRUE)
test = read.table("VTaxo.txt", header=TRUE)
testb <- as.matrix(test[,-1])
TAX <- tax_table(testb)
physeq <- phyloseq(mytable, envdata, tree, TAX)
SAR.all <- subset_taxa(physeq, Tt2 == c("Alv","Str","Rhi"))
din.all <- subset_taxa(physeq, Tt3 == c("Din"))
core.all <- subset_taxa(physeq, Genus == c("Corethron")) # only microsize fraction here

pico <- subset_samples(physeq, size == "pico")
nano <- subset_samples(physeq, size == "nano")
micro <- subset_samples(physeq, size == "micro")
#PCoA <- ordinate(physeq, "PCoA", distance = "canberra")
dUNIFRAC = UniFrac(physeq, weighted=TRUE, normalized=FALSE, fast=TRUE)
PCoA <- ordinate(physeq, "PCoA", distance = dUNIFRAC)
ordplotP <- plot_ordination(physeq, PCoA, color="Lat", shape="size",label="sample", title="Allsize")
ordplotPplus <- ordplotP + geom_point(size=3) + stat_ellipse(geom = "polygon", type="norm", alpha=0.4, aes(fill=size))
quartz()
plot(ordplotPplus)

#PCoAm <- ordinate(micro, "PCoA", distance = "canberra")
dUNIFRACm = UniFrac(micro, weighted=TRUE, normalized=FALSE, fast=TRUE)
PCoAm <- ordinate(micro, "PCoA", distance = dUNIFRACm)
ordplotPm <- plot_ordination(micro, PCoAm, color="Lat", shape="depth",label="sample",title="Micropk")
ordplotPmplus <- ordplotPm + geom_point(size=3) + stat_ellipse(geom = "polygon", type="norm", alpha=0.4, aes(fill=depth))
quartz()
plot(ordplotPmplus)

#PCoAn <- ordinate(nano, "PCoA", distance = "canberra")
dUNIFRACn = UniFrac(nano, weighted=TRUE, normalized=FALSE, fast=TRUE)
PCoAn <- ordinate(nano, "PCoA", distance = dUNIFRACn)
ordplotPn <- plot_ordination(nano, PCoAn, color="Lat", shape="depth",label="sample",title="Nanopk")
quartz()
plot(ordplotPn)

#PCoAn <- ordinate(nano, "PCoA", distance = "canberra")
dUNIFRACp = UniFrac(pico, weighted=TRUE, normalized=FALSE, fast=TRUE)
PCoAp <- ordinate(pico, "PCoA", distance = dUNIFRACp)
ordplotPp <- plot_ordination(pico, PCoAp, color="Lat", shape="depth",label="sample",title="Picopk")
quartz()
plot(ordplotPp)

#quartz()
#map.df <- data.frame(sample_data(physeq))
#orddataPa <- ordplotP$data
#ordPpa.ef <- envfit(PCoA$vectors~station,permutations=1000,data= map.df)
#ordPca.ef <- envfit(PCoA$vectors~size,permutations=1000,data= map.df)
#plot(x=orddataPa$Axis.1, y=orddataPa$Axis.2,type="n")
#points(PCoA$vectors[,1],PCoA$vectors[,2], cex=0.5, col=map.df$size, pch=19)
#ordiellipse(PCoA$vectors, map.df$size,label=TRUE,cex=0.7,conf=0.99,col="yellow")

#envfit for each parameters in my env_data table (+)
ordMDS <- metaMDS(t(otu_table(physeq)))
ordMDS.fit <- envfit(ordMDS ~ bottom + ice + airT + depth_m + size_num +  depSM + waterT1 + conductivity1 + oxygen1 +  fluorescence +  beamTrans + PAR1 +  latitude +  longitude +  timeJ +  altM +  spar + salinity1 + oxygenSaturation + bprod + pprod_Sun + pprod_PAR, data=sample.data.table(physeq), perm=999, na.rm = TRUE)
plot(ordMDS, dis="site")
plot(ordMDS.fit)
text(ordMDS, display="sites")
ordMDS.fit

#adonis for some parameters and their interaction (*)
Adonis.results = adonis(formula = distance(physeq, "jaccard") ~ size * Group * latitude * layer, data = as(sample_data(physeq), "data.frame"), permutations = 9999) 
cat("Adonis_results", capture.output(Adonis.results), file="summary_of_Adonis_results.txt", sep="n", append=TRUE)
