setwd('~/Desktop/RWS_0001-0096_outin/R_more100')
library('ape')
library('phyloseqCompanion')
#library("phyloseq")
#library("foreach")
#library("iterators")
#library("parallel")
#library("doParallel")
library("ggplot2")
library("plyr")
#library("vegan")
data.all <- read.table('OTUtable_ingroup.txt')
mytable = otu_table(data.all, taxa_are_rows=TRUE,errorIfNULL=TRUE)
env.all <- read.table('NBP1910_envdata.txt')
envdata = sample_data(env.all)
tree <- read.tree('rename.tree')
phy_tree(tree, errorIfNULL=TRUE)
test = read.table("Blast_result_renamed.txt", header=TRUE)
testb <- as.matrix(test[,-1])
TAX <- tax_table(testb)
physeq <- phyloseq(mytable, envdata, tree, TAX)
pico <- subset_samples(physeq, size == "pico")
nano <- subset_samples(physeq, size == "nano")
micro <- subset_samples(physeq, size == "micro")

ordMDSa <- metaMDS(t(data.all))
orda.fit <- envfit(ordMDSa ~ size, data=data.all, perm=999)
ord <- cca(t(data.all) ~ size + Lat * Long, data=env.all)
anova(ord, by="term", permutations=999)
plot(ord)
ordiellipse(ord, size, col=1:4, kind="ehull", lwd=3, label=TRUE)

ordMDS <- metaMDS(t(otu_table(nano)))
ordMDS.fit <- envfit(ordMDS ~ Lat + Long + ice + air.temp + depth_m, data=sample.data.table(nano), perm=999)
plot(ordMDS, dis="site")
plot(ordMDS.fit)
text(ordMDS, display="sites")
ordMDS.fit