
#if issue with phyloseq and ape
#install.packages("devtools")
#devtools::install_github("joey711/phyloseq")
#library("phyloseq")


setwd("/Users/tuk61790/Documents/JD_work/JayDiii_R/DGGE_cop")
library('ape')
library("phyloseq")
library("foreach")
library("iterators")
library("parallel")
library("doParallel")
library("ggplot2")
library("plyr")
library("vegan")
data.all <- read.table('OTU_HTS.txt')
mytable = otu_table(data.all, taxa_are_rows=TRUE,errorIfNULL=TRUE)
env.all <- read.table('HTS_env.txt')
envdata = sample_data(env.all)
tree <- read.tree('Tree_HTS_R.tree')
phy_tree(tree, errorIfNULL=TRUE)
test = read.table("Tax_table_doris.txt", header=TRUE)
testb <- as.matrix(test[,-1])
TAX <- tax_table(testb)

physeq <- phyloseq(mytable, envdata, TAX, tree)

nano <- subset_samples(physeq, Size == "Nanosize")
micro <- subset_samples(physeq, Size == "Microsize")


#treedraw <- plot_tree(physeq, color="Cop", shape="incubation", size="Abundance", ladderize = TRUE, justify="left", title="Size")
#quartz()
#plot(treedraw)

#dUNIFRAC = UniFrac(physeq, weighted=FALSE, normalized=FALSE, fast=TRUE)
#PCoA <- ordinate(physeq, "PCoA", distance = dUNIFRAC)
PCoA <- ordinate(physeq, "NMDS", distance = "jaccard", binary=TRUE)
ordplotP <- plot_ordination(physeq, PCoA, color="Treatment", shape="Size",label="Sample")
quartz()
plot(ordplotP)
PCoAn <- ordinate(nano, "NMDS", distance = "jaccard", binary=TRUE)
ordplotPn <- plot_ordination(nano, PCoAn, color="Treatment", label="Sample",title = "Spnanosize")
quartz()
plot(ordplotPn)
#PCoAm <- ordinate(micro, "NMDS", distance = "jaccard", binary=TRUE)
NMDSm <- ordinate(micro, "NMDS", distance = "jaccard", binary=TRUE)
ordplotPm <- plot_ordination(micro, NMDSm, color="Treatment", label="Sample", title="SpMicrosize")
quartz()
plot(ordplotPm)
map.df <- data.frame(sample_data(micro))
#orddataPa <- ordplotPm$data
#ordPpa.ef <- envfit(PCoAm$vectors~Treatment,permutations=1000,data= map.df)
ordPpa.ef <- envfit(NMDSm~Treatment,permutations=1000,data= map.df)
#quartz()
#plot(x=orddataPa$Axis.1, y=orddataPa$Axis.2,type="n")
#plot(x=orddataPa$NMDS1, y=orddataPa$NMDS2,type="n")
#points(PCoAm$vectors[,1],PCoAm$vectors[,2], cex=0.5, col=map.df$Treatment,pch=19)
#points(orddataPa$NMDS1,orddataPa$NMDS2, cex=0.5, col=map.df$Treatment,pch=19)
#ordihull(NMDSm, map.df$Treatment,label=TRUE,cex=0.7,col=map.df$Treatment)

#ordiellipse(NMDSm, map.df$Treatment,label=TRUE,cex=0.7,conf=0.99,col="gray50")
#ordiellipse(NMDSm, map.df$Treatment,label=TRUE,cex=0.7,conf=0.95,col="gray60")
#ordiellipse(NMDSm, map.df$Treatment,label=TRUE,cex=0.7,conf=0.90,col="gray70")
#ordiellipse(NMDSm, map.df$Treatment,label=TRUE,cex=0.7,conf=0.80,col="gray80")
#ordiellipse(NMDSm, map.df$Treatment,label=TRUE,cex=0.7,conf=0.50,col="gray90")
#ordiellipse(PCoAm$vectors, map.df$Treatment,label=TRUE,cex=0.7,conf=0.50,col="gray90")