setwd("/Users/tuk61790/Documents/JD_work/JayDiii_R/DGGE_cop")
library('ape')
library("phyloseq")
library("foreach")
library("iterators")
library("parallel")
library("doParallel")
library("ggplot2")
library("plyr")
library("vegan")
data.all <- read.table('OTU_HTS.txt')
mytable = otu_table(data.all, taxa_are_rows=TRUE,errorIfNULL=TRUE)
env.all <- read.table('HTS_env.txt')
envdata = sample_data(env.all)
tree <- read.tree('Tree_HTS_R.tree')
phy_tree(tree, errorIfNULL=TRUE)
test = read.table("Tax_table_doris.txt", header=TRUE)
testb <- as.matrix(test[,-1])
TAX <- tax_table(testb)

physeq <- phyloseq(mytable, envdata, TAX, tree)
#metadata <- as(sample_data(physeq), "data.frame")
#nano <- subset_samples(physeq, Size == "Nanosize")
#micro <- subset_samples(physeq, Size == "Microsize")
#metadatan <- as(sample_data(nano), "data.frame")
#metadatam <- as(sample_data(micro), "data.frame")

Tvc <- subset_samples(physeq, change == "no") 
CvT <- subset_samples(physeq, P == "yes") 
metadata <- as(sample_data(Tvc), "data.frame")
nano <- subset_samples(Tvc, Size == "Nanosize")
micro <- subset_samples(Tvc, Size == "Microsize")
metadatan <- as(sample_data(nano), "data.frame")
metadatam <- as(sample_data(micro), "data.frame")

distus <- "wunifrac"
print(distus)
#PERMANOVA <- adonis(distance(physeq, method=distus) ~ Treatment*Size, data = metadata)
PERMANOVA <- adonis(distance(Tvc, method=distus) ~ Treatment*Size, data = metadata)
#PERMANOVA <- adonis(distance(physeq, method=distus) ~ Incubation, data = metadata)
print(PERMANOVA)
PERMANOVAn <- adonis(distance(nano, method=distus) ~ Treatment, data = metadatan)
print(PERMANOVAn)
PERMANOVAm <- adonis(distance(micro, method=distus) ~ Treatment, data = metadatam)
print(PERMANOVAm)
