setwd('/Users/katzlab3003/Documents/JD_Grattepanche/metatranscriptomics/MiSeq_MeMi/R_MeMi_June2017')
library('ape')
library("phyloseq")
library("foreach")
library("iterators")
library("parallel")
library("doParallel")
library("ggplot2")
library("plyr")
library("vegan")
data.all <- read.table('OTUtable_ingroup_sept.txt')
mytable = otu_table(data.all, taxa_are_rows=TRUE,errorIfNULL=TRUE)
env.all <- read.table('env_Memi_august2018_pooled.txt')
envdata = sample_data(env.all)
tree <- read.tree('RAxML_labelledTree.test_MiSeq2018R.tre')
phy_tree(tree, errorIfNULL=TRUE)
test = read.table("TaxonomyMeMi2.txt", header=TRUE)
testb <- as.matrix(test[,-1])
TAX <- tax_table(testb)
physeq <- phyloseq(mytable, envdata, tree, TAX)
nano <- subset_samples(physeq, size == "Nano")
micro <- subset_samples(physeq, size == "micro")
#PCoA <- ordinate(physeq, "PCoA", distance = "canberra")
dUNIFRAC = UniFrac(physeq, weighted=FALSE, normalized=FALSE, fast=TRUE)
PCoA <- ordinate(physeq, "PCoA", distance = dUNIFRAC)
ordplotP <- plot_ordination(physeq, PCoA, color="Phytoplankton", shape="Copepods",label="sample")
quartz()
plot(ordplotP)
#PCoAm <- ordinate(micro, "PCoA", distance = "canberra")
dUNIFRACm = UniFrac(micro, weighted=FALSE, normalized=FALSE, fast=TRUE)
PCoAm <- ordinate(micro, "PCoA", distance = dUNIFRACm)
ordplotPm <- plot_ordination(micro, PCoAm, color="Phytoplankton", shape="Copepods",label="sample")
quartz()
plot(ordplotPm)
#PCoAn <- ordinate(nano, "PCoA", distance = "canberra")
dUNIFRACn = UniFrac(nano, weighted=FALSE, normalized=FALSE, fast=TRUE)
PCoAn <- ordinate(nano, "PCoA", distance = dUNIFRACn)
ordplotPn <- plot_ordination(nano, PCoAn, color="Phytoplankton", shape="Copepods",label="sample")
quartz()
plot(ordplotPn)

quartz()
map.df <- data.frame(sample_data(physeq))
orddataPa <- ordplotP$data
ordPpa.ef <- envfit(PCoA$vectors~Phytoplankton,permutations=1000,data= map.df)
ordPca.ef <- envfit(PCoA$vectors~Copepods,permutations=1000,data= map.df)
plot(x=orddataPa$Axis.1, y=orddataPa$Axis.2,type="n")
points(PCoA$vectors[,1],PCoA$vectors[,2], cex=0.5, col=map.df$Phytoplankton,pch=19)
ordiellipse(PCoA$vectors, map.df$Phytoplankton,label=TRUE,cex=0.7,conf=0.99,col="yellow")


quartz()
mapn.df <- data.frame(sample_data(nano))
orddataPn <- ordplotPn$data
ordPpn.ef <- envfit(PCoAn$vectors~Phytoplankton,permutations=1000,data= mapn.df)
ordPcn.ef <- envfit(PCoAn$vectors~Copepods,permutations=1000,data= mapn.df)
plot(x=orddataPn$Axis.1, y=orddataPn$Axis.2,type="n")
points(PCoAn$vectors[,1],PCoAn$vectors[,2], cex=0.5, col=mapn.df$Phytoplankton,pch=19)
ordiellipse(PCoAn$vectors, mapn.df$Phytoplankton,label=TRUE,cex=0.7,conf=0.99,col="yellow")

quartz()
mapm.df <- data.frame(sample_data(micro))
orddataPm <- ordplotPm$data
ordPpm.ef <- envfit(PCoAm$vectors~Phytoplankton,permutations=1000,data= mapm.df)
ordPcm.ef <- envfit(PCoAm$vectors~Copepods,permutations=1000,data= mapm.df)
plot(x=orddataPm$Axis.1, y=orddataPm$Axis.2,type="n")
points(PCoAm$vectors[,1],PCoAm$vectors[,2], cex=0.5, col=mapm.df$Phytoplankton,pch=19)
ordiellipse(PCoAm$vectors, mapm.df$Phytoplankton,label=TRUE,cex=0.7,conf=0.99,col="yellow")
