#if issue with phyloseq and ape
#install.packages("devtools")
#devtools::install_github("joey711/phyloseq")
#library("phyloseq")


setwd('/Users/katzlab3003/Documents/JD_Grattepanche/metatranscriptomics/MiSeq_MeMi/R_MeMi_June2017')
library('ape')
library("phyloseq")
library("foreach")
library("iterators")
library("parallel")
library("doParallel")
library("ggplot2")
library("plyr")
library("vegan")
data.all <- read.table('OTUtable_ingroup_sept.txt')
mytable = otu_table(data.all, taxa_are_rows=TRUE,errorIfNULL=TRUE)
env.all <- read.table('env_Memi_august2018_pooled.txt')
envdata = sample_data(env.all)
tree <- read.tree('RAxML_labelledTree.test_MiSeq2018R.tre')
phy_tree(tree, errorIfNULL=TRUE)
test = read.table("TaxonomyMeMi2.txt", header=TRUE)
testb <- as.matrix(test[,-1])
TAX <- tax_table(testb)
physeq <- phyloseq(mytable, envdata, tree, TAX)
nano <- subset_samples(physeq, size == "micro")
alv <- subset_taxa(nano, Ttaxo_rank2 == "Alv")
cil <- subset_taxa(alv, Ttaxo_rank3 == "Ci")
str <- subset_taxa(nano, Ttaxo_rank2 == "Str")
bac <- subset_taxa(str, Ttaxo_rank3 == "Ba")
dic <- subset_taxa(str, Ttaxo_rank3 == "Di")
rhi <- subset_taxa(nano, Ttaxo_rank2 == "Rhi")


dUNIFRAC.alv = UniFrac(alv, weighted=TRUE, normalized=FALSE, fast=TRUE)
PCoA.alv <- ordinate(alv, "PCoA", distance = dUNIFRAC.alv)
#ordplotP.alv <- plot_ordination(alv, PCoA.alv, color="Phytoplankton", shape="Copepods",label="sample")
#quartz()
#plot(ordplotP.alv)
mapa.df <- data.frame(sample_data(alv))
print("alv")
print(envfit(PCoA.alv$vectors~Copepods,permutations=1000,data= mapa.df))
print(envfit(PCoA.alv$vectors~Phytoplankton,permutations=1000,data= mapa.df))

dUNIFRAC.cil = UniFrac(cil, weighted=TRUE, normalized=FALSE, fast=TRUE)
PCoA.cil <- ordinate(cil, "PCoA", distance = dUNIFRAC.cil)
#ordplotP.cil <- plot_ordination(cil, PCoA.cil, color="Phytoplankton", shape="Copepods",label="sample")
#quartz()
#plot(ordplotP.cil)
mapc.df <- data.frame(sample_data(cil))
print("cil")
print(envfit(PCoA.cil$vectors~Copepods,permutations=1000,data= mapc.df))
print(envfit(PCoA.cil$vectors~Phytoplankton,permutations=1000,data= mapc.df))

dUNIFRAC.str = UniFrac(str, weighted=TRUE, normalized=FALSE, fast=TRUE)
PCoA.str <- ordinate(str, "PCoA", distance = dUNIFRAC.str)
#ordplotP.str <- plot_ordination(str, PCoA.str, color="Phytoplankton", shape="Copepods",label="sample")
#quartz()
#plot(ordplotP.str)
maps.df <- data.frame(sample_data(str))
print("str")
print(envfit(PCoA.str$vectors~Copepods,permutations=1000,data= maps.df))
print(envfit(PCoA.str$vectors~Phytoplankton,permutations=1000,data= maps.df))

dUNIFRAC.bac = UniFrac(bac, weighted=TRUE, normalized=FALSE, fast=TRUE)
PCoA.bac <- ordinate(bac, "PCoA", distance = dUNIFRAC.bac)
#ordplotP.bac <- plot_ordination(bac, PCoA.bac, color="Phytoplankton", shape="Copepods",label="sample")
#quartz()
#plot(ordplotP.bac)
mapb.df <- data.frame(sample_data(bac))
print("bac")
print(envfit(PCoA.bac$vectors~Copepods,permutations=1000,data= mapb.df))
print(envfit(PCoA.bac$vectors~Phytoplankton,permutations=1000,data= mapb.df))

dUNIFRAC.dic = UniFrac(dic, weighted=TRUE, normalized=FALSE, fast=TRUE)
PCoA.dic <- ordinate(dic, "PCoA", distance = dUNIFRAC.dic)
#ordplotP.dic <- plot_ordination(dic, PCoA.dic, color="Phytoplankton", shape="Copepods",label="sample")
#quartz()
#plot(ordplotP.dic)
mapd.df <- data.frame(sample_data(dic))
print("dic")
print(envfit(PCoA.dic$vectors~Copepods,permutations=1000,data= mapd.df))
print(envfit(PCoA.dic$vectors~Phytoplankton,permutations=1000,data= mapd.df))

dUNIFRAC.rhi = UniFrac(rhi, weighted=TRUE, normalized=FALSE, fast=TRUE)
PCoA.rhi <- ordinate(rhi, "PCoA", distance = dUNIFRAC.rhi)
#ordplotP.rhi <- plot_ordination(rhi, PCoA.rhi, color="Phytoplankton", shape="Copepods",label="sample")
#quartz()
#plot(ordplotP.rhi)
mapr.df <- data.frame(sample_data(rhi))
print("rhi")
print(envfit(PCoA.rhi$vectors~Copepods,permutations=1000,data= mapr.df))
print(envfit(PCoA.rhi$vectors~Phytoplankton,permutations=1000,data= mapr.df))
